### PR TITLE
Make it watch

### PR DESCRIPTION
**Pull request by latentflip**
Depends on #62 and probably needs tests or something.

### CODE REVIEW

**Comment by faiq** [comment]
@wraithgar can you please point me to where you used it! I'm really confused :disappointed: on how I should be using it.

**Comment by wraithgar** [comment]
https://github.com/wraithgar/moonboots_hapi/blob/master/index.js#L74
then in the actual handler
https://github.com/wraithgar/moonboots_hapi/blob/master/index.js#L80-L85

**Comment by wraithgar** [comment]
Now that I look at your comment again it seems that doesn't solve your specific problem maybe

**Comment by lukekarrys** [comment]
@latentflip This is great! And I really want it to land to save me from long build times in developmentMode. So I added a commit to address the following:

- watchify has a default of false and always gets set to false if developmentMode is false
- added `watchify:true` to the dev test and and added a test that requests the `jsSource` twice to make sure 1) it doesnt break and 2) it gets coverage up to 100% because then it can set `bundle` to `self.watchedBundle`.

Anything else that needs to get discussed for this? Should we go ahead and update to v8 of browserify now that its out?

**Comment by faiq** [comment]
@latentflip, how did **you** solve the concerns I posted above, I would really love some guidance. :D

**Comment by lukekarrys** [comment]
I pulled this branch into my current project using `moonboots_hapi` and encountered an error when using it with the `modulesDir` option (which uses `browserify.require` and the `expose` option).

It looks like the result of this bug with `watchify`: https://github.com/substack/watchify/issues/72.

I'm gonna come up with a failing test and then see if one of the workarounds in that issue will fix it.

**Comment by lukekarrys** [comment]
I made a failing test where if you get `jsSource()` twice for a watchified bundle, the bundles are different and any file exposed as part of `modulesDir` wont be able to be required properly.

I tried updating browserify and watchify to see if any of the workarounds in the issue above worked, but none of them did.

Seems like the only way watchify could be included is if we detect both `modulesDir` and `watchify` in the config, we throw an error. Otherwise it'll lead to hard to track down bugs where users just get `{}` as the result of requiring a module. But that seems like not a great idea.

Keeping an eye on the related watchify issues:
- https://github.com/substack/watchify/issues/72
- https://github.com/substack/watchify/issues/74
- https://github.com/substack/watchify/issues/122

**Pull request closed without merging**
